### ISSUE TITLE
Problem with TLSv1

### ISSUE THREAD

**Issue by kmarko9** [aszadzinski/xmppy#1]
After using console command

```console
user@H:~$ xmppy -j  *******@**.** -p ***** -t ***@**.**-m "test" 
```

I got KeyError message

```
INFO     Negotiating TLS
ERROR    Connection error.
ERROR    <_SSLMethod.PROTOCOL_TLSv1_2: 5>
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1490, in _process
    if not self.__read_xml():
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1562, in __read_xml
    self.__spawn_event(xml)
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1630, in __spawn_event
    handler.prerun(stanza_copy)
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 64, in prerun
    self.run(payload, True)
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/features/feature_starttls/starttls.py", line 64, in _handle_starttls_proceed
    if self.xmpp.start_tls():
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 843, in start_tls
    log.info("Using SSL version: %s", ssl_versions[self.ssl_version])
KeyError: <_SSLMethod.PROTOCOL_TLSv1_2: 5>
INFO     Waiting for </stream:stream> from server
^CTraceback (most recent call last):
  File "/tmp/venv/bin/xmppy", line 8, in <module>
    sys.exit(main())
  File "/tmp/venv/lib/python3.10/site-packages/xmppy/Messenger.py", line 184, in main
    xmpp = Client.sendMessage(opts.jid, opts.password,
  File "/tmp/venv/lib/python3.10/site-packages/xmppy/Messenger.py", line 89, in sendMessage
    instance = cls(jid, password, recipient, message,
  File "/tmp/venv/lib/python3.10/site-packages/xmppy/Messenger.py", line 58, in __init__
    self.run(wait)
  File "/tmp/venv/lib/python3.10/site-packages/xmppy/Messenger.py", line 72, in run
    self.process(block=True)
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/basexmpp.py", line 245, in process
    return XMLStream.process(self, *args, **kwargs)
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1463, in process
    self._process()
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1520, in _process
    self.reconnect()
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 763, in reconnect
    self.state.transition('connected', 'disconnected',
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/thirdparty/statemachine.py", line 73, in transition
    return self.transition_any((from_state,), to_state, wait=wait,
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/thirdparty/statemachine.py", line 119, in transition_any
    return_val = func(*args,**kwargs) if func is not None else True
  File "/tmp/venv/lib/python3.10/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 725, in _disconnect
    self.stream_end_event.wait(4)
  File "/usr/lib/python3.10/threading.py", line 600, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1560, in _shutdown
    lock.acquire()
```

For python3.9 everything works fine

**Comment by Athalbraht** [comment]
solved
